// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var add_list, get_forms;
    add_list = function() {
      var add_text, add_words;
      add_text = $('#input_add').val();
      add_words = add_text.split(/[,\s]/).filter(function(e) {
        if (!e) {
          return false;
        }
        $(".wordbox").each(function() {
          if ($(this).val() === e) {
            return false;
          }
        });
        return true;
      });
      add_words = $.unique(add_words);
      $(".wordbox").each(function() {
        console.log(add_words);
        if (!$(this).val()) {
          $(this).val(add_words.shift());
          if (add_words.length === 0) {
            return false;
          }
        }
      });
      return $('#input_add').val("");
    };
    $('#submit-add').click(add_list);
    get_forms = function() {
      var data, game_description, game_name, wordlist, words_text, words_unit;
      wordlist = [];
      $('.wordbox').each(function() {
        var v;
        v = $.trim($(this).val());
        if (v) {
          return wordlist.push(v);
        }
      });
      words_text = wordlist.join(',');
      game_name = $.trim($('#input_game_name').val());
      words_unit = $.trim($('#input_words_unit').val());
      game_description = $.trim($('#input_description').val());
      if (words_text !== '' && (game_name != null) && (words_unit != null) && game_description) {
        return data = {
          game_name: game_name,
          words_unit: words_unit,
          game_description: game_description,
          words_list_text: words_text
        };
      }
      return false;
    };
    $('#check-btn').click(function() {
      var gn, ok;
      ok = true;
      if (gn = $.trim($('#input_game_name').val())) {
        gn;
      } else {
        ok = false;
      }
      $('#input_words_unit').val();
      return $('#input_descripiton').val();
    });
    return $('#submit-btn').click(function() {
      var data;
      if (!(data = get_forms())) {
        console.log('form no comp');
        return false;
      }
      return $.ajax({
        type: "POST",
        url: "make/post",
        data: data,
        success: function(data) {
          return console.log(data);
        },
        error: function() {
          return console.log('connect error');
        }
      });
    });
  });

}).call(this);
